on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: Djipyy/amd-pr-checkbox@v1
      with:
        pat: ${{ secrets.PAT }}
        merging_pr_number: ${{ github.event.pull_request.number }}
        merging_pr_repository: ${{ github.event.pull_request.head.repo.full_name }}