name: Python Virtual Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Create_Env1:
    runs-on: ubuntu-latest
    steps:
    - uses: Djipyy/amd-composite-action@v1
      with:
        python-version: '3.10'
        requirements-file: 'requirements.txt'

  Create_Env2:
    runs-on: ubuntu-latest
    steps:
    - uses: Djipyy/amd-composite-action@v1
      with:
        python-version: '3.9'
        requirements-file: 'requirements.txt'
        constraints: |
            lxml==4.6.3
        requirements: |
            numpy

